version: '3.8'

services:
   postgresdb:
      container_name: postgresdb
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_DB: ${PSQL_DATABASE}
         POSTGRES_USER: ${PSQL_USER}
         POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      ports:
         - '${PSQL_PORT_TCP}:5432'
      volumes:
         - pg-data:/var/lib/postgresql/data
         - ${PSQL_BACKUPS}:/backups
         # - ./init.sh:/docker-entrypoint-initdb.d/init.sh

   backup:
      build:
         context: .
         dockerfile: Dockerfile
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${PSQL_USER}
         POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      volumes:
         - ${PSQL_BACKUPS}:/backups
      depends_on:
         - postgresdb

volumes:
   pg-data:
      name: psql_pg-data
      driver: local
