version: '3.8'

services:
   mysqldb:
      container_name: mysqldb
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_DATABASE: 'db'
         MYSQL_USER: 'dev'
         MYSQL_PASSWORD: 'mypassdev81'
         MYSQL_ROOT_PASSWORD: 'devchallenge81'
      ports:
         - '3306:3306'
      volumes:
         - my-db:/var/lib/mysql
         - ./db/example.sql:/docker-entrypoint-initdb.d/example.sql
      logging:
         driver: none

volumes:
   my-db:
      driver: local